//
//  ContentView.swift
//  Password Manager
//
//  Created by Kishore Shiva Saravanan on 08/12/24.
//

import SwiftUI
import FirebaseFirestore
import FirebaseAuth

struct ContentView: View {
    
    @State private var isLoggedIn = true
    @State private var dataBoxes = [DataBox]()
    @State private var showEditForm = false
    @State private var showPopup = false // State to show the pop-up
    @State private var editClicked = false // State to show the pop-up
    @State private var searchClicked = false
    @State private var searchText = ""
    @FocusState private var isSearchFieldFocused: Bool
    
    static var editDataBox: DataBox? = nil
    
    let emptyDataBox = DataBox(
        id: "", // The ID is auto-generated by Firebase, so you can ignore this
        topic: "",
        UsernameOrCardNo: "",
        mailId: "",
        passwordOrPin: "",
        additionalDetails: ""
    )
    
    var body: some View {
        if isLoggedIn {
            ZStack{
                VStack(spacing: 0){
                    
                    if(!searchClicked){
                        // Top bar with lock icon, title, and search button
                        HStack {
                            Spacer()
                            HStack {
                                Image(systemName: "lock.shield")
                                    .font(.title)
                                    .foregroundColor(.orange)
                                Text("Password Manager")
                                    .font(.headline)
                                    .foregroundStyle(.white)
                            }
                            Spacer()
                            Button(action: {
                                // Add search button action here
                                searchClicked = true
                                isSearchFieldFocused = true
                            }) {
                                Image(systemName: "magnifyingglass.circle")
                                    .foregroundColor(.orange)
                                    .font(.title2)
                            }
                        }
                        .padding(.horizontal)
                        .frame(height: 40) // Slightly smaller height
                        .background(Color.black)
                    }
                    else{
                        HStack{
                            Image(systemName: "magnifyingglass")
                                .padding()
                            
                            Spacer()
                            
                            TextField("Search here", text: $searchText)
                            .padding(5)
                            .cornerRadius(8)
                            .overlay(
                                RoundedRectangle(cornerRadius: 8)
                                    .stroke(Color.gray, lineWidth: 1)
                            )
                            .focused($isSearchFieldFocused)
                            .onChange(of: searchText) { newValue in
                                            filterDataBoxes(by: newValue)
                                        }
                            
                            Spacer()
                            
                            Button(action: {
                                isSearchFieldFocused = false
                                searchClicked = false
                            }){
                                Image(systemName: "xmark.circle.fill")
                                    .padding()
                            }
                        }
                        .padding(.horizontal)
                        .frame(height: 40) // Slightly smaller height
                    }
                    
                    //Top Bar with photo, name and sign-out button
                    HStack {
                        // User photo
                        if let url = URL(string: FirebaseModel().getUserPhotoURL()) {
                            AsyncImage(url: url) { phase in
                                switch phase {
                                case .empty:
                                    ProgressView()
                                        .frame(width: 40, height: 40)
                                        .background(Color.gray)
                                        .clipShape(Circle())
                                case .success(let image):
                                    image
                                        .resizable()
                                        .frame(width: 40, height: 40)
                                        .clipShape(Circle())
                                case .failure:
                                    Image(systemName: "person.circle.fill")
                                        .resizable()
                                        .frame(width: 40, height: 40)
                                        .clipShape(Circle())
                                @unknown default:
                                    EmptyView()
                                }
                            }
                        } else {
                            Image(systemName: "person.circle.fill")
                                .resizable()
                                .frame(width: 40, height: 40)
                                .clipShape(Circle())
                        }
                        
                        // User name
                        Text(FirebaseModel().getUserName())
                            .font(.headline)
                            .foregroundColor(.white)
                            .padding(.leading, 8)
                        
                        Spacer()
                        
                        // Sign Out button
                        Button(action: {
                            // Add sign-out functionality here
                            signOut()
                            isLoggedIn = false
                        }) {
                            Text("Sign Out")
                                .font(.subheadline)
                                .foregroundColor(.white)
                                .padding(8)
                                .background(Color.gray.opacity(0.3))
                                .cornerRadius(5)
                        }
                    }
                    .padding()
                    .background(Color.black)
                    
                    // Full-width "Add new credentials" button
                    Button(action: {
                        // Add action for "Add new credentials" button here
                        
                        updateShowPopup(value: true)
                    }) {
                        Text("Add new credentials")
                            .font(.title2)
                            .foregroundColor(.white)
                            .padding()
                            .frame(maxWidth: .infinity, maxHeight: 45)
                            .background(Color.orange)
                            .cornerRadius(10)
                    }
                    .padding(.horizontal, 10)
                    .padding(.top, 10)
                    .padding(.bottom, 6)
                    // Optional for spacing between the buttons
                    
                    // Black box with rounded corners and orange border
                    ScrollView {
                                VStack {
                                    ForEach(dataBoxes) { dataBox in
                                        DataBoxView(dataBox: dataBox, contentView: self)
                                    }
                                }
                                .onAppear {
                                    updateDataBoxes()
                                }
                            }
                    
                    Spacer()
                }
                
                // Overlay for the pop-up with transparency effect
                if showPopup {
                    Color.black.opacity(0.8) // Semi-transparent overlay
                        .edgesIgnoringSafeArea(.all)
                        .onTapGesture {
                            editClicked = false
                            showPopup = false // Close pop-up when tapping outside
                        }
                    if(editClicked){
                        EditOrCreateForm(dataBox: ContentView.editDataBox, contentView: self)
                    }
                    else{
                        EditOrCreateForm(dataBox: emptyDataBox, contentView: self)
                    }
                }
            }
        }
        else{
            LoginPage()
        }
    }
    
    func updateShowPopup(value: Bool) {
            showPopup = value
        }
    
    func updateEditClicked(value: Bool){
        editClicked = value
    }
    func getEditClicked() -> Bool{
        return editClicked
    }
    
    func updateDataBoxes(){
        print("inside ContentView() updateDataBoxes")
        dataBoxes = []
        FirebaseModel().fetchData { fetchedData in
            dataBoxes = fetchedData
            print("updated dataBoxes: \(self.dataBoxes)")
        }
    }
    
    func filterDataBoxes(by partialTopic: String) {
        if !(partialTopic.isEmpty) {
            // Perform case-insensitive search and update the filtered list
            dataBoxes = FirebaseModel().getDataBoxes().filter {
                $0.topic.lowercased().contains(partialTopic.lowercased())
            }
        }
    }
    
    func signOut() {
        do{
            try Auth.auth().signOut()
        }
        catch{
            print("Error: SignOut() ---> \(error.localizedDescription)")
        }
    }
}

#Preview {
    ContentView()
}
